on:
  workflow_dispatch:

jobs:
  dsv-retrieve-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Read secret
        id: get
        uses: DelineaXPM/dsv-github-action@v2.0.2
        with:
          domain: ${{ secrets.DSV_SERVER }}
          clientId: ${{ secrets.DSV_CLIENT_ID }}
          clientSecret: ${{ secrets.DSV_CLIENT_SECRET }}
          retrieve: |
            [
             {"secretPath": "${{ secrets.DSV_SECRET_PATH }}", "secretKey": "${{ secrets.DSV_SECRET_DATA_KEY }}", "outputVariable": "SECRET0"},
             {"secretPath": "github-secret/secret1", "secretKey": "key1", "outputVariable": "SECRET1"},
             {"secretPath": "github-secret/secret1", "secretKey": "key2", "outputVariable": "SECRET2"}
            ]
      - name: Print secrets
        run: echo ${{ env.SECRET0 }}
            echo ${{ env.SECRET1 }}
            echo ${{ env.SECRET2 }}
      - name: check github-secret/secret1 key1
        id: key1
        if: "contains(env.SECRET1, 'val1')"
        run: echo "ok!"
      - name: check github-secret/secret1 key2
        id: key2
        if: "contains(env.SECRET2, 'val2')"
        run: echo "ok!"
